#spring:
#  datasource:
#    url: jdbc:mysql://175.24.47.171:3306/gmall_pms?useUnicode=true&useSSL=false&characterEncoding=utf8
#    driver-class-name: com.mysql.jdbc.Driver
#    password: 3852159
#    username: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.109.1:8848


