 #
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://175.24.47.171:3306/gmall_ums?useUnicode=true&useSSL=false&characterEncoding=utf8
#    username: root
#    password: 3852159
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
